# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roberto Villarejo Martínez
email: robertovillarejo@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog where to document my knowledege and experience
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robertovillarejo.github.io" # the base hostname & protocol for your site
twitter_username: RobertoVillarej
github_username:  robertovillarejo

# Build settings
markdown: kramdown
